apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: test
 template:
  metadata:
   labels:
    app: test
  spec:
   containers:
    - name: mycon
      image: asoni007/maven-web-application:1
      ports:
       - containerPort: 8080
      readinessProbe:
       httpGet:
        path: /maven-web-application
        port: 8080
       initialDelaySeconds: 15
       periodSeconds: 15
      livenessProbe:
       httpGet:
        path: /maven-web-application
        port: 8080
       initialDelaySeconds: 15
       periodSeconds: 15
       timeoutSeconds: 1
